In [36]:
import numpy as np

In [37]:
lista = [0,1,2,3,4,5,6,7,8,9,10]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [38]:
arr=np.array(lista)

In [39]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:

matriz[1]


array([4, 5, 6])

In [41]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [42]:
arr[1:6:2] 

array([1, 3, 5])

In [43]:
arr= np.array([1,2,3,4], dtype='float64')
arr.dtype
arr

array([1., 2., 3., 4.])

In [44]:
arr = np.array(lista)
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [45]:
arr = np.array(lista)
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10'],
      dtype='|S11')

In [46]:
arr = np.array(lista)
arr = arr.astype(np.float64)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])