In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
condition1 = arr > 5
arr[condition]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [6]:
condition2= arr <=8
arr[(condition1)&(condition2)]

array([6, 7, 8], dtype=int8)

In [7]:
arr[(arr<8)]

array([1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [9]:
arr[arr>5] = 52
arr

array([ 1,  2,  3,  4,  5, 52, 52, 52, 52, 52], dtype=int8)

In [10]:
arr[arr == 52]

array([52, 52, 52, 52, 52], dtype=int8)