In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand()

0.17736064035793675

In [12]:
np.random.rand(3,3)

array([[0.889853  , 0.42169298, 0.7442408 ],
       [0.69474351, 0.07863116, 0.72293338],
       [0.85686319, 0.87232958, 0.55608048]])

In [13]:
np.random.randint(1,15)

6

In [14]:
np.random.randint(1,15,(3,3))

array([[11, 13,  7],
       [14,  2,  1],
       [10, 10, 13]])