In [13]:
import numpy as np

In [14]:
arr = np.random.randint(1,20,10)
arr

array([12,  4,  8,  1,  5,  5, 18, 15, 18, 14])

In [15]:
matriz = arr.reshape(2,5)
matriz

array([[12,  4,  8,  1,  5],
       [ 5, 18, 15, 18, 14]])

In [16]:
arr.max()

18

In [17]:
matriz.max()

18

In [18]:
matriz.max(1)
#por fila 1

array([12, 18])

In [19]:
matriz.max(0)
#por columna 0

array([12, 18, 15, 18, 14])

In [20]:
arr.argmax()
#posicion en el array del vectos

6

In [21]:
matriz.argmax()

6

In [22]:
matriz.argmax(0)

array([0, 1, 1, 1, 1], dtype=int64)

In [23]:
arr.min()

1

In [24]:
arr.ptp()
#el valor mas alto contra el valor mas bajo de mi array

17

In [26]:
matriz.ptp(1)
#lo hace por filas

array([11, 13])

In [30]:
np.percentile(arr,50)
#se suman los dos valores de la mitad y se dividen

10.0

In [31]:
arr.sort()
arr
#aqui puedes ver los dos valores de la mitad o el de la mitad

array([ 1,  4,  5,  5,  8, 12, 14, 15, 18, 18])

In [32]:
np.median(arr)
#donde se encuentra la mitad de la distribución 

10.0

In [33]:
np.median(matriz,1)

array([ 5., 15.])

In [34]:
np.std(arr)
#desviación estandar

5.865151319446072

In [35]:
np.var(arr)
#varianza

34.4

In [36]:
x=np.std(arr)**2
x
#la varianza es la desviación standard al cuadrado

34.400000000000006

In [37]:
np.mean(arr)
#la media es la operación la suma de todos los valores 
#dividido entre el numero totales de valores

10.0

In [60]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
a

array([[1, 2],
       [3, 4]])

In [61]:
b= np.expand_dims(b,axis=1)

In [62]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])