In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [6]:
arr = np.arange(0,10)
arr2 = arr[:]
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
matriz = arr.reshape(2,5)
matriz2 = matriz[:] #es iguala matriz.copy()

In [10]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [11]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [12]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [13]:
matriz @ matriz2.T
#producto punto de dos matrices

array([[ 30,  80],
       [ 80, 255]])