In [11]:
import numpy as np

In [12]:
arr = np.random.randint(1,10,(3,4))

In [13]:
arr.shape

(3, 4)

In [14]:
arr

array([[7, 2, 4, 6],
       [4, 1, 9, 3],
       [2, 4, 9, 1]])

In [16]:
arr.reshape(1,12)

array([[7, 2, 4, 6, 4, 1, 9, 3, 2, 4, 9, 1]])

In [17]:
arr.reshape(2,6)

array([[7, 2, 4, 6, 4, 1],
       [9, 3, 2, 4, 9, 1]])

In [21]:
np.reshape(arr,(2,6),'C')
#ordena por filas

array([[7, 2, 4, 6, 4, 1],
       [9, 3, 2, 4, 9, 1]])

In [22]:
np.reshape(arr,(2,6),'F')
#ordena por columna

array([[7, 2, 1, 4, 9, 3],
       [4, 2, 4, 9, 6, 1]])

In [23]:
arr

array([[7, 2, 4, 6],
       [4, 1, 9, 3],
       [2, 4, 9, 1]])

In [26]:
np.reshape(arr,(2,6),'A')

array([[7, 2, 4, 6, 4, 1],
       [9, 3, 2, 4, 9, 1]])